新規登録できないエラー
Yugenn/laravel_crm pull request #1
Opened 2021-09-29 11:12 UTC by Yugenn

新規登録ができなくなってしまいましたが、調べても原因がわかりませんでした。

2021-09-29 11:38 UTC, kazu-taka commented on app/Http/Controllers/ZipController.php
> +            // フラッシュメッセージ
@Yugenn 
tryの中のどこかでエラーになっていて、backメソッドで前の画面に戻ってるだけではないですかね！？
`dd($th)`のでエラーの内容を確認してみて下さい🙏

2021-09-29 12:44 UTC, Yugenn commented
完成したのでスクリーンショットを貼り付けます

<img width="1280" alt="スクリーンショット 2021-09-29 21 33 25" src="https://user-images.githubusercontent.com/89439437/135270541-3a29661b-acad-4d14-bf94-3e846fef594b.png">
<img width="1280" alt="スクリーンショット 2021-09-29 21 33 42" src="https://user-images.githubusercontent.com/89439437/135270559-94e8ad9d-ec4c-444c-911d-b04a99da3601.png">
<img width="1280" alt="スクリーンショット 2021-09-29 21 36 33" src="https://user-images.githubusercontent.com/89439437/135270569-ff78a8a3-6fac-4b8a-9fd0-d402633af5ed.png">
<img width="1280" alt="スクリーンショット 2021-09-29 21 37 40" src="https://user-images.githubusercontent.com/89439437/135270578-6edcea8f-7630-4838-89af-0b23bc8fc4d3.png">
<img width="1280" alt="スクリーンショット 2021-09-29 21 32 36" src="https://user-images.githubusercontent.com/89439437/135270581-10ef5b80-e7d4-4e99-a0d2-e1552dbddf12.png">

<img width="1280" alt="スクリーンショット 2021-09-29 21 37 55" src="https://user-images.githubusercontent.com/89439437/135270591-93d4a19d-661a-4c86-a0c8-e77a27f70dd0.png">
<img width="1280" alt="スクリーンショット 2021-09-29 21 38 22" src="https://user-images.githubusercontent.com/89439437/135270606-0e449a3a-bb82-4008-8612-39f75b6358b6.png">

2021-09-29 19:55 UTC, kazu-taka requested changes
@Yugenn 
コメントしたので修正お願いします🙏

2021-09-29 19:55 UTC, kazu-taka commented on app/Http/Controllers/ZipController.php
> +                $zip = new Zip();
@Yugenn 
インデントの修正お願いします！

2021-09-29 19:55 UTC, kazu-taka commented on app/Http/Requests/ZipRequest.php
> +            'postcode' => 'required|integer|',
@Yugenn 
郵便番号は7桁なので、minとmaxの指定があってもいいと思います✨

2021-09-29 19:55 UTC, kazu-taka commented on database/migrations/2021_09_27_010017_create_zips_table.php
> +            $table->string('phoneNumber');
@Yugenn 
カラム名は、`phone_numbder`のようにスネークケースで書くようにして下さい✨

2021-09-29 19:55 UTC, kazu-taka commented on resources/views/zips/edit.blade.php
> +            <input type="text" name="email" id="email" value="{{ $zip->email }}">
@Yugenn 
メールアドレスはtype="email"の方が良いです✨

2021-09-29 19:55 UTC, kazu-taka commented on resources/views/zips/form.blade.php
> +            <input type="text" name="email" id="email" value="{{ old('email') }}">
@Yugenn 
同じくtype="email"で！

2021-09-29 19:55 UTC, kazu-taka commented on resources/views/zips/edit.blade.php
> +            <input type="text" name="name" id="name" value="{{ $zip->name }}">
@Yugenn 
old関数も合わせて使用しないと、バリデーションでエラーになった時に、入力した内容が元にもどってしまうので、修正お願いします！(他の項目も)

2021-09-30 03:35 UTC, kazu-taka approved these changes
@Yugenn 
CSSの読み込み場所を全てチェックし、修正して頂けたらマージしてOKです✨

2021-09-30 03:35 UTC, kazu-taka commented on resources/views/zips/show.blade.php
> +<link rel="stylesheet" href="{{ asset('css/style.css') }}">
@Yugenn 
CSSはmain.blade.phpのheadタグ内で読み込むように修正お願いします！

2021-09-30 03:56 UTC, merged